import Foundation
import Testing
@testable import BreviariumKit
@testable import BreviariumDataCore

// Diffs engine output against data/oracle-fixtures/ (generated by
// scripts/generate-oracle-fixtures.sh against the pinned Divinum Officium checkout).
@Test func oracleTargetIsWired() {
    #expect(breviariumKitDataFormatVersion > 0)
}

/// The real bundle, built once per test run from the pinned checkout — `nil` (and every
/// test below skips) if the submodule isn't checked out.
private enum RealCorpus {
    static let bundle: DataBundle? = {
        let checkoutRoot = OracleFixture.repoRoot.appendingPathComponent("data/divinum-officium")
        guard FileManager.default.fileExists(atPath: checkoutRoot.path) else { return nil }
        return try? BreviariumDataPipeline.build(checkoutRoot: checkoutRoot)
    }()
}

/// Flattens a `BreviariumKit.Unit` to the plain-text piece(s) comparable against a DO
/// oracle fixture (HTML-stripped, whitespace-collapsed prose) — as *separate* strings
/// for `.versicleResponse` rather than one joined string, since the real fixture has
/// DO's own `℣.`/`℟.` glyph directly between them (confirmed against the real oracle
/// fixture for 16 September 2026: our own design deliberately drops those labels
/// entirely, per `CLAUDE.md`'s visual spec, so a single joined "versicle response"
/// string is never actually contiguous in DO's rendered text). `.verse` reconstructs
/// the original `" * "` half-verse spacing `Psalm.splitHalves` drops when attaching the
/// asterisk directly to the first half for display, since the fixture still has DO's
/// raw spacing.
private func oracleComparisonTexts(_ unit: BreviariumKit.Unit) -> [String] {
    switch unit {
    case .rubric(let text, _): return [text]
    case .versicleResponse(let versicle, let response, _, _): return [versicle, response]
    case .verse(_, let first, let second, _, _):
        guard !second.isEmpty else { return [first] }
        let withoutAsterisk = first.hasSuffix("*") ? String(first.dropLast()) : first
        return ["\(withoutAsterisk) * \(second)"]
    case .antiphon(let text, _): return [text]
    case .prose(let text, _): return [text]
    }
}

private func collapsedWhitespace(_ text: String) -> String {
    // "+" is DO's own source-text placeholder for the cross gesture in a handful of
    // fixed invocations (Deus in adiutorium, the Magnificat's opening verse); its real
    // rendering substitutes the "✠" glyph. That substitution is a presentation-layer
    // choice (which glyph to actually draw), not liturgical content, so it's normalised
    // away here rather than replicated in the Kit's own text data.
    text.replacingOccurrences(of: "✠", with: "+")
        .split(whereSeparator: { $0.isWhitespace })
        .joined(separator: " ")
}

/// Every comparable text piece in `hour` that isn't found anywhere in `fixtureText` --
/// empty means a clean diff. `fixtureText` gets `LatinOrthography` applied here (the
/// fixtures are deliberately stored pre-normalisation — `data/SOURCE.md` — precisely so
/// this comparison is the one place that needs to run it).
private func mismatches(hour: Hour, fixtureText: String, sectionKinds: Set<Section.Kind>? = nil) -> [String] {
    let normalizedFixture = collapsedWhitespace(LatinOrthography.normalize(fixtureText))
    var mismatches: [String] = []
    for section in hour.sections where sectionKinds?.contains(section.kind) ?? true {
        for unit in section.units {
            for piece in oracleComparisonTexts(unit) {
                let text = collapsedWhitespace(piece)
                guard !text.isEmpty else { continue }
                if !normalizedFixture.contains(text) {
                    mismatches.append("[\(section.kind)] \(text)")
                }
            }
        }
    }
    return mismatches
}

/// Known, documented gaps this first pass doesn't cover (`docs/PLAN.md`'s M4 status has
/// the full story from each one's discovery) — excluded from comparison scope per test
/// below rather than silently passing on content we already know can be wrong:
///
/// - `.psalmodia`/`.canticum` on dates outside the one below they're confirmed against:
///   antiphon-source selection has more rank/season-dependent rules than
///   `assemblePsalmodia`'s current one covers (see its own doc comment for what's
///   confirmed and what's traced-but-unconfirmed, e.g. the `"ex"`-gated Commune
///   extension for a second-Vespers `[Ant Vespera 3]`).
@Test func martyrsFeastMatchesTheRealOracleFor16September2026() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pentecosten", feria: 4, ad: "vesperas", mense: 9)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 16, month: 9, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-09-16"))
    // .oratio now in scope: confirmed real that Ss. Cornelii et Cypriani's collect is
    // Commune/C3.txt's own [Oratio 3] (second Vespers), name-substituted -- see
    // assemblePsalmodia's doc comment for the full discovery writeup.
    // .versus now in scope too: [Versum 3] (-> Commune/C3's own [Versum 2] via its own
    // cross-reference), not the [Versum 1] this code used to return unconditionally --
    // see assembleCapitulumHymnusVersus's doc comment.
    let diff = mismatches(
        hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .psalmodia, .canticum, .oratio, .capitulum, .hymnus, .versus, .conclusio]
    )
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func plainFeriaMatchesTheRealOracleFor19January2026() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Epiphaniam", feria: 2, ad: "vesperas", mense: 1)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 19, month: 1, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-01-19"))
    // .psalmodia excluded here: this date's psalms (114/119) are exactly the ones
    // Psalm.swift's own doc comment already flags as a deliberately deferred scope
    // limit -- verses the Bea psalter splits more finely than the plain numbering
    // (e.g. "114:14"/"(15)"), which this pass doesn't yet merge into one aligned unit.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .canticum, .oratio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func agathaMatchesTheRealOracleIncludingTheNameSubstitutedCollect() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Epiphaniam", feria: 5, ad: "vesperas", mense: 2)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 5, month: 2, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-02-05"))
    // .psalmodia excluded: the antiphon/psalm-number selection itself is confirmed
    // correct here (109, 110, 111, 112, 147, exactly matching the real fixture) -- the
    // remaining mismatch is entirely within Psalm 111's own verse text, which hits the
    // same Bea/Vulgate half-verse-numbering gap "19 January" already excludes for
    // (Psalm.swift's own doc comment), not a new issue this date introduces.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .canticum, .oratio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func ashWednesdayShowsTheRealPrecesFerialesText() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "Quadragesima", feria: 4, ad: "vesperas", mense: 2)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 18, month: 2, year: 2026, priest: false))

    let precesFeriales = try #require(hour.sections.first { $0.kind == .precesFeriales })
    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-02-18"))
    let diff = mismatches(hour: Hour(sections: [precesFeriales]), fixtureText: fixtureText, sectionKinds: [.precesFeriales])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    // The Pope/Bishop name placeholder is confirmed left literal by DO's own real
    // output (no dynamic "reigning Pope" data source exists even there) -- not a gap.
    #expect(precesFeriales.units.contains { if case .versicleResponse(let v, _, _, _) = $0 { return v.contains("Papa nostro N.") } else { return false } })
}

@Test func sundayWithinTheChristmasOctaveUsesNat1_0sOwnAntiphonsFor28December2025() async throws {
    // 2025-12-28 is the one day that year the Sunday within the Christmas Octave
    // falls on (Occurrence.temporalPath's own "26-31 December" redirect, added
    // 2026-09-17 after finding real DO output never reaches the plain day-numbered
    // "Nat28" file here at all). Holy Innocents (Sancti/12-28, rank 5.4) and the
    // Sunday (via Nat1-0, also 5.4) are exactly tied under 1960 rubrics, so this also
    // exercises that the Sunday's *real* rank -- not some other file's -- is what the
    // occurrence comparison actually sees.
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "Nativitas", feria: 1, ad: "vesperas", mense: 12)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 28, month: 12, year: 2025, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2025, date: "2025-12-28"))
    // .psalmodia excluded from the full diff: Psalm 111 (one of this day's five) hits
    // the same already-documented Bea/Vulgate half-verse-numbering gap the 19
    // January/Agatha tests already exclude it for -- not a new issue this date
    // introduces. The antiphon-selection assertion below is independent of that gap.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    #expect(psalmodia.units.contains(.antiphon("Tecum princípium * in die virtútis tuæ, in splendóribus sanctórum, ex útero ante lucíferum génui te.")))
}

@Test func plainPaschaltideWeekdayReplacesPsalmAntiphonsWithAllelúia() async throws {
    // 20 April 2026: a plain ferial Monday within Paschaltide (week "Pasc2", IV.
    // classis, no Sancti office) -- confirmed real fixture shows every psalm antiphon
    // as alleluia_ant()'s "Allelúia, * allelúia, allelúia." rather than the plain
    // ferial schedule's own text.
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pascha", feria: 2, ad: "vesperas", mense: 4)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 20, month: 4, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-04-20"))
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    let alleluiaCount = psalmodia.units.filter { $0 == .antiphon("Allelúia, * allelúia, allelúia.") }.count
    #expect(alleluiaCount == 10, "expected all 5 psalms bracketed by the Allelúia antiphon (open+close each), found \(alleluiaCount)")
}

@Test func englishSectionsMatchTheRealBilingualFixtureFor16September2026() async throws {
    // CLAUDE.md's own visual-spec worked example, checked here against the bilingual
    // spot-check fixture (Latin and English are two separate blocks per section in
    // DO's own rendering, not interleaved verse-by-verse -- confirmed by inspecting the
    // raw fixture directly). English is compared against the *unnormalised* fixture
    // text: LatinOrthography.normalize (J-to-I) must never touch English (CLAUDE.md:
    // "Never touch English"), so running it over this bilingual fixture as a whole
    // would risk corrupting real English words containing "j" (e.g. "rejoice").
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pentecosten", feria: 4, ad: "vesperas", mense: 9)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar), englishCorpus: bundle.makeEnglishCorpus())
    let hour = try #require(assembler.assembleVespers(day: 16, month: 9, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.spotCheck(filename: "2026-09-16_priestN_bilingual_visual-spec-example.txt"))
    let normalizedFixture = collapsedWhitespace(fixtureText.replacingOccurrences(of: "✠", with: "+"))

    func englishTexts(_ unit: BreviariumKit.Unit) -> [String] {
        switch unit {
        case .rubric(_, let english): return [english].compactMap { $0 }
        case .versicleResponse(_, _, let v, let r): return [v, r].compactMap { $0 }
        case .verse(_, _, _, let first, let second):
            guard let first, let second else { return [] }
            guard !second.isEmpty else { return [first] }
            let withoutAsterisk = first.hasSuffix("*") ? String(first.dropLast()) : first
            return ["\(withoutAsterisk) * \(second)"]
        case .antiphon(_, let english): return [english].compactMap { $0 }
        case .prose(_, let english): return [english].compactMap { $0 }
        }
    }

    var missing: [String] = []
    for section in hour.sections
    where [.introductio, .psalmodia, .canticum, .oratio, .capitulum, .hymnus, .versus, .conclusio].contains(section.kind) {
        for unit in section.units {
            for piece in englishTexts(unit) {
                let text = collapsedWhitespace(piece)
                guard !text.isEmpty else { continue }
                if !normalizedFixture.contains(text) { missing.append("[\(section.kind)] \(text)") }
            }
        }
    }
    #expect(missing.isEmpty, "\(missing.count) English unit(s) not found in the bilingual fixture:\n\(missing.joined(separator: "\n"))")

    // At least one real English unit was actually produced and checked per wired
    // section, not just an empty (vacuously passing) diff.
    let introductio = try #require(hour.sections.first { $0.kind == .introductio })
    #expect(introductio.units.contains(.versicleResponse(
        versicle: "Deus + in adiutórium meum inténde.", response: "Dómine, ad adiuvándum me festína.",
        versicleEnglish: "O God, + come to my assistance;", responseEnglish: "O Lord, make haste to help me."
    )))

    let canticum = try #require(hour.sections.first { $0.kind == .canticum })
    #expect(canticum.units.contains(.antiphon(
        "Gaudent in cælis * ánimæ Sanctórum, qui Christi vestígia sunt secúti: et quia pro eius amóre sánguinem suum fudérunt, ídeo cum Christo exsúltant sine fine.",
        english: "In heaven do rejoice the souls of the Saints * who have followed the steps of Christ; and because they shed their blood for the love of Christ, therefore shall they be made glad for ever with Christ."
    )))
    // The Magnificat itself (Luke 1:46-55, New Testament) has no Bea/Vulgate numbering
    // divergence to worry about -- its own verses pair cleanly. This specifically
    // covers a real bug found via this exact assertion: Psalm232.txt's own leading
    // "(Canticum B. Mariæ Virginis * Luc. 1:46-55)" title-comment line was being
    // misparsed by ConditionalLineProcessor as a false (sed ...)-style condition,
    // silently swallowing verse "1:46" itself -- fixed by SectionResolver.resolvePsalmText
    // reading psalm/canticle text raw, bypassing conditional-line processing entirely,
    // matching DO's own real behaviour (horasscripts.pl's plain do_read for these files).
    #expect(canticum.units.contains {
        if case .verse(let ref, _, _, let firstEnglish, _) = $0 { return ref == "1:46" && firstEnglish != nil } else { return false }
    })
    // Psalm 127 (this office's own weekday psalm) does NOT pair, and this is a real,
    // confirmed data-quality issue in the pinned DO checkout, not our bug: the Bea
    // Latin-Bea/Psalterium/Psalmorum/Psalm127.txt mislabels its own 4th verse as
    // "127:3" (a bare repeat of the number, immediately after "127:3a"/"127:3b") instead
    // of "127:4", breaking the exact reference-sequence match against English's clean
    // "127:1,2,3a,3b,4,5,6". Confirming this falls back to Latin-only (not a silently
    // wrong pairing) is the point of this assertion.
    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    let psalm127Verses = psalmodia.units.filter { if case .verse(let ref, _, _, _, _) = $0 { return ref.hasPrefix("127:") } else { return false } }
    #expect(!psalm127Verses.isEmpty)
    #expect(psalm127Verses.allSatisfy { if case .verse(_, _, _, let firstEnglish, _) = $0 { return firstEnglish == nil } else { return false } })
    // The Gloria doxology that follows Psalm 127 is fixed, 2-line, and always pairs
    // positionally regardless of any psalm-specific numbering divergence.
    #expect(psalmodia.units.contains {
        if case .verse(let ref, _, _, let firstEnglish, _) = $0 { return ref.isEmpty && firstEnglish != nil } else { return false }
    })

    // The versicle itself is a real, confirmed DO English-tree gap, not our bug:
    // Commune/C3.txt's English side has no [Versum 3] at all (only [Versum 1]/[Versum
    // 2] directly) even though its Latin side does (as `@:Versum 2`, confirmed a
    // universal alias pattern across Commune/C1.txt/C1p.txt/C2.txt/C4.txt/C5.txt, but
    // *not* universal on real office files -- several alias to Versum 1 instead, and
    // some carry a genuinely distinct versicle -- so this can't be simplified to always
    // querying "Versum 2" directly). Correctly resolving `resolvedLocation`'s "same
    // exact section" rule here means English stays nil rather than guessing.
    let versus = try #require(hour.sections.first { $0.kind == .versus })
    #expect(versus.units.contains(.versicleResponse(versicle: "Exsultábunt Sancti in glória.", response: "Lætabúntur in cubílibus suis.")))
}

@Test func easterSundayIntroductioAndConclusioMatchTheRealOracleWithPriestForm() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pascha", feria: 1, ad: "vesperas", mense: 4)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 5, month: 4, year: 2026, priest: true))

    let fixtureText = try #require(try await OracleFixture.shared.spotCheck(filename: "2026-04-05_priestY_latin_easter.txt"))
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

// `ConditionalContextBuilder` is the missing piece that lets the app call `HourAssembler`
// for an arbitrary date, rather than every test above's own hand-set `ConditionalContext`
// (which several of these fixtures show were themselves only approximations -- e.g.
// "Quadragesima"/"Nativitas"/"post Pascha" above are not DO's own real `tempore` strings,
// just placeholders good enough for the sections those specific tests compare). These
// checks confirm the builder reproduces the *real* DO values -- `feria` against this
// file's own already-verified hand-set contexts, `tempore`/`die` against `SetupString.pl`
// traced directly (`ConditionalContextBuilder.swift`'s own doc comments cite the exact
// lines).
@Test func contextBuilderMatchesTheRealSeasonAndFeriaFor16September2026() throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let calendar = SanctoralCalendar(entries: bundle.calendar)
    let context = ConditionalContextBuilder.build(
        day: 16, month: 9, year: 2026, ad: "vesperas", rubrica: "Rubrics 1960 - 1960", corpus: corpus, sanctoralCalendar: calendar
    )
    #expect(context.tempore == "post Pentecosten")
    #expect(context.feria == 4)
    #expect(context.mense == 9)
}

@Test func contextBuilderMatchesTheRealSeasonAndFeriaFor19January2026() throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let calendar = SanctoralCalendar(entries: bundle.calendar)
    let context = ConditionalContextBuilder.build(
        day: 19, month: 1, year: 2026, ad: "vesperas", rubrica: "Rubrics 1960 - 1960", corpus: corpus, sanctoralCalendar: calendar
    )
    // Not "post Epiphaniam": that bare value only comes from DO's own February branch
    // (`SetupString.pl:189`) -- 14 January through 2 February is "...post partum"
    // (`SetupString.pl:188`, the GABC "post partum" chant period), which is what this
    // date's own hand-set placeholder context above ("post Epiphaniam", never itself
    // verified against DO's real tempusID) got only approximately right.
    #expect(context.tempore == "post Epiphaniam post partum")
    #expect(context.feria == 2)
}

@Test func contextBuilderNamesChristmasAndEpiphanyAndAllSoulsForTheDieField() throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let calendar = SanctoralCalendar(entries: bundle.calendar)
    func die(_ day: Int, _ month: Int, _ year: Int) -> String {
        ConditionalContextBuilder.build(
            day: day, month: month, year: year, ad: "vesperas", rubrica: "Rubrics 1960 - 1960", corpus: corpus, sanctoralCalendar: calendar
        ).die
    }
    // First Vespers of Epiphany falls on 5 January (`$vesp_or_comp` true for Vespers).
    #expect(die(5, 1, 2026) == "Epiphaniæ")
    #expect(die(6, 1, 2026) == "Epiphaniæ")
    #expect(die(25, 12, 2026) == "Nativitatis")
    #expect(die(2, 11, 2026) == "Omnium Defunctorum")
    #expect(die(3, 11, 2026) == "Malachiae")
    #expect(die(4, 11, 2026) == "Caroli")
}

@Test func stElisabethsVespersUsesTheRealCommuneC7PsalmsAndHasACapitulumHymnusVersus() throws {
    // Real bug, found via a full visual walkthrough of 19 November 2026 (S. Elisabeth
    // Viduæ, "vide C7a"): Commune/C7a.txt defines only its own Mass-proper overrides,
    // leaning on its own preamble's "@Commune/C7" whole-file inclusion for
    // [Ant Vespera]/[Hymnus Vespera]/etc. -- a do-format.md-documented mechanism that
    // was never actually implemented, so the engine silently fell through to the plain
    // ferial psalm schedule (wrong psalms, no verses for the second one at all) and
    // dropped Hymnus/Versus entirely. Fixed in SectionResolver via RawOfficeFile.baseFile.
    //
    // Capitulum is deliberately NOT asserted here: it turns out `[Capitulum Vespera]`
    // genuinely doesn't exist anywhere in the C1-C11 commune family on disk (confirmed:
    // grepped every Commune/*.txt -- only C12/C12A define one; C7/C7a/C6, and even
    // Ss. Cornelii et Cypriani's own Commune/C3 from the 16 September fixture, only ever
    // carry Capitulum Laudes/Sexta/Nona). What DO's real Vespers actually falls back to
    // in that case is a separate, deeper question `assembleCapitulumHymnusVersus`'s own
    // doc comment already flags as untraced -- not something this whole-file-inclusion
    // fix addresses, and not guessed at here.
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let calendar = SanctoralCalendar(entries: bundle.calendar)
    let context = ConditionalContextBuilder.build(
        day: 19, month: 11, year: 2026, ad: "vesperas", rubrica: "Rubrics 1960 - 1960", corpus: corpus, sanctoralCalendar: calendar
    )
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: calendar)
    let hour = try #require(assembler.assembleVespers(day: 19, month: 11, year: 2026, priest: false))

    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    let antiphonTexts = psalmodia.units.compactMap { unit -> String? in
        if case .antiphon(let text, _) = unit { return text } else { return nil }
    }
    #expect(antiphonTexts.contains { $0.contains("Dum esset Rex") })
    #expect(!antiphonTexts.contains { $0.contains("Ecce quam bonum") })
    // Vespers has 5 psalms, each bracketed by its own antiphon (open + close) --
    // 10 antiphon units total. Checking the real count directly, since a UI-level
    // screenshot walkthrough can't distinguish "only 1 psalm assembled" from "5
    // psalms assembled but only 1 fit in the captured viewport".
    #expect(antiphonTexts.count == 10, "\(antiphonTexts.count) antiphon units: \(antiphonTexts)")
    let verseCount = psalmodia.units.filter { if case .verse = $0 { return true } else { return false } }.count
    #expect(verseCount > 4, "only \(verseCount) verse units across all 5 psalms + doxologies")

    let hymnus = try #require(hour.sections.first { $0.kind == .hymnus })
    #expect(!hymnus.units.isEmpty)
    let hymnusText = hymnus.units.compactMap { unit -> String? in
        if case .prose(let text, _) = unit { return text } else { return nil }
    }.joined(separator: " ")
    #expect(hymnusText.contains("Fortem viríli péctore"))

    let versus = try #require(hour.sections.first { $0.kind == .versus })
    #expect(!versus.units.isEmpty)
}
