import Foundation
import Testing
@testable import BreviariumKit
@testable import BreviariumDataCore

// Diffs engine output against data/oracle-fixtures/ (generated by
// scripts/generate-oracle-fixtures.sh against the pinned Divinum Officium checkout).
@Test func oracleTargetIsWired() {
    #expect(breviariumKitDataFormatVersion > 0)
}

/// The real bundle, built once per test run from the pinned checkout — `nil` (and every
/// test below skips) if the submodule isn't checked out.
private enum RealCorpus {
    static let bundle: DataBundle? = {
        let checkoutRoot = OracleFixture.repoRoot.appendingPathComponent("data/divinum-officium")
        guard FileManager.default.fileExists(atPath: checkoutRoot.path) else { return nil }
        return try? BreviariumDataPipeline.build(checkoutRoot: checkoutRoot)
    }()
}

/// Flattens a `BreviariumKit.Unit` to the plain-text piece(s) comparable against a DO
/// oracle fixture (HTML-stripped, whitespace-collapsed prose) — as *separate* strings
/// for `.versicleResponse` rather than one joined string, since the real fixture has
/// DO's own `℣.`/`℟.` glyph directly between them (confirmed against the real oracle
/// fixture for 16 September 2026: our own design deliberately drops those labels
/// entirely, per `CLAUDE.md`'s visual spec, so a single joined "versicle response"
/// string is never actually contiguous in DO's rendered text). `.verse` reconstructs
/// the original `" * "` half-verse spacing `Psalm.splitHalves` drops when attaching the
/// asterisk directly to the first half for display, since the fixture still has DO's
/// raw spacing.
private func oracleComparisonTexts(_ unit: BreviariumKit.Unit) -> [String] {
    switch unit {
    case .rubric(let text): return [text]
    case .versicleResponse(let versicle, let response): return [versicle, response]
    case .verse(_, let first, let second):
        guard !second.isEmpty else { return [first] }
        let withoutAsterisk = first.hasSuffix("*") ? String(first.dropLast()) : first
        return ["\(withoutAsterisk) * \(second)"]
    case .antiphon(let text): return [text]
    case .prose(let text): return [text]
    }
}

private func collapsedWhitespace(_ text: String) -> String {
    // "+" is DO's own source-text placeholder for the cross gesture in a handful of
    // fixed invocations (Deus in adiutorium, the Magnificat's opening verse); its real
    // rendering substitutes the "✠" glyph. That substitution is a presentation-layer
    // choice (which glyph to actually draw), not liturgical content, so it's normalised
    // away here rather than replicated in the Kit's own text data.
    text.replacingOccurrences(of: "✠", with: "+")
        .split(whereSeparator: { $0.isWhitespace })
        .joined(separator: " ")
}

/// Every comparable text piece in `hour` that isn't found anywhere in `fixtureText` --
/// empty means a clean diff. `fixtureText` gets `LatinOrthography` applied here (the
/// fixtures are deliberately stored pre-normalisation — `data/SOURCE.md` — precisely so
/// this comparison is the one place that needs to run it).
private func mismatches(hour: Hour, fixtureText: String, sectionKinds: Set<Section.Kind>? = nil) -> [String] {
    let normalizedFixture = collapsedWhitespace(LatinOrthography.normalize(fixtureText))
    var mismatches: [String] = []
    for section in hour.sections where sectionKinds?.contains(section.kind) ?? true {
        for unit in section.units {
            for piece in oracleComparisonTexts(unit) {
                let text = collapsedWhitespace(piece)
                guard !text.isEmpty else { continue }
                if !normalizedFixture.contains(text) {
                    mismatches.append("[\(section.kind)] \(text)")
                }
            }
        }
    }
    return mismatches
}

/// Known, documented gaps this first pass doesn't cover (`docs/PLAN.md`'s M4 status has
/// the full story from each one's discovery) — excluded from comparison scope per test
/// below rather than silently passing on content we already know can be wrong:
///
/// - `.psalmodia`/`.canticum` on dates outside the one below they're confirmed against:
///   antiphon-source selection has more rank/season-dependent rules than
///   `assemblePsalmodia`'s current one covers (see its own doc comment for what's
///   confirmed and what's traced-but-unconfirmed, e.g. the `"ex"`-gated Commune
///   extension for a second-Vespers `[Ant Vespera 3]`).
@Test func martyrsFeastMatchesTheRealOracleFor16September2026() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pentecosten", feria: 4, ad: "vesperas", mense: 9)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 16, month: 9, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-09-16"))
    // .oratio now in scope: confirmed real that Ss. Cornelii et Cypriani's collect is
    // Commune/C3.txt's own [Oratio 3] (second Vespers), name-substituted -- see
    // assemblePsalmodia's doc comment for the full discovery writeup.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .psalmodia, .canticum, .oratio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func plainFeriaMatchesTheRealOracleFor19January2026() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Epiphaniam", feria: 2, ad: "vesperas", mense: 1)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 19, month: 1, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-01-19"))
    // .psalmodia excluded here: this date's psalms (114/119) are exactly the ones
    // Psalm.swift's own doc comment already flags as a deliberately deferred scope
    // limit -- verses the Bea psalter splits more finely than the plain numbering
    // (e.g. "114:14"/"(15)"), which this pass doesn't yet merge into one aligned unit.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .canticum, .oratio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func agathaMatchesTheRealOracleIncludingTheNameSubstitutedCollect() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Epiphaniam", feria: 5, ad: "vesperas", mense: 2)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 5, month: 2, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-02-05"))
    // .psalmodia excluded: the antiphon/psalm-number selection itself is confirmed
    // correct here (109, 110, 111, 112, 147, exactly matching the real fixture) -- the
    // remaining mismatch is entirely within Psalm 111's own verse text, which hits the
    // same Bea/Vulgate half-verse-numbering gap "19 January" already excludes for
    // (Psalm.swift's own doc comment), not a new issue this date introduces.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .canticum, .oratio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}

@Test func ashWednesdayShowsTheRealPrecesFerialesText() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "Quadragesima", feria: 4, ad: "vesperas", mense: 2)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 18, month: 2, year: 2026, priest: false))

    let precesFeriales = try #require(hour.sections.first { $0.kind == .precesFeriales })
    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-02-18"))
    let diff = mismatches(hour: Hour(sections: [precesFeriales]), fixtureText: fixtureText, sectionKinds: [.precesFeriales])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    // The Pope/Bishop name placeholder is confirmed left literal by DO's own real
    // output (no dynamic "reigning Pope" data source exists even there) -- not a gap.
    #expect(precesFeriales.units.contains { if case .versicleResponse(let v, _) = $0 { return v.contains("Papa nostro N.") } else { return false } })
}

@Test func sundayWithinTheChristmasOctaveUsesNat1_0sOwnAntiphonsFor28December2025() async throws {
    // 2025-12-28 is the one day that year the Sunday within the Christmas Octave
    // falls on (Occurrence.temporalPath's own "26-31 December" redirect, added
    // 2026-09-17 after finding real DO output never reaches the plain day-numbered
    // "Nat28" file here at all). Holy Innocents (Sancti/12-28, rank 5.4) and the
    // Sunday (via Nat1-0, also 5.4) are exactly tied under 1960 rubrics, so this also
    // exercises that the Sunday's *real* rank -- not some other file's -- is what the
    // occurrence comparison actually sees.
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "Nativitas", feria: 1, ad: "vesperas", mense: 12)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 28, month: 12, year: 2025, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2025, date: "2025-12-28"))
    // .psalmodia excluded from the full diff: Psalm 111 (one of this day's five) hits
    // the same already-documented Bea/Vulgate half-verse-numbering gap the 19
    // January/Agatha tests already exclude it for -- not a new issue this date
    // introduces. The antiphon-selection assertion below is independent of that gap.
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    #expect(psalmodia.units.contains(.antiphon("Tecum princípium * in die virtútis tuæ, in splendóribus sanctórum, ex útero ante lucíferum génui te.")))
}

@Test func plainPaschaltideWeekdayReplacesPsalmAntiphonsWithAllelúia() async throws {
    // 20 April 2026: a plain ferial Monday within Paschaltide (week "Pasc2", IV.
    // classis, no Sancti office) -- confirmed real fixture shows every psalm antiphon
    // as alleluia_ant()'s "Allelúia, * allelúia, allelúia." rather than the plain
    // ferial schedule's own text.
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pascha", feria: 2, ad: "vesperas", mense: 4)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 20, month: 4, year: 2026, priest: false))

    let fixtureText = try #require(try await OracleFixture.shared.main(year: 2026, date: "2026-04-20"))
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")

    let psalmodia = try #require(hour.sections.first { $0.kind == .psalmodia })
    let alleluiaCount = psalmodia.units.filter { $0 == .antiphon("Allelúia, * allelúia, allelúia.") }.count
    #expect(alleluiaCount == 10, "expected all 5 psalms bracketed by the Allelúia antiphon (open+close each), found \(alleluiaCount)")
}

@Test func easterSundayIntroductioAndConclusioMatchTheRealOracleWithPriestForm() async throws {
    guard let bundle = RealCorpus.bundle else { return }
    let corpus = bundle.makeLatinCorpus()
    let context = ConditionalContext(rubrica: "Rubrics 1960 - 1960", tempore: "post Pascha", feria: 1, ad: "vesperas", mense: 4)
    let assembler = HourAssembler(corpus: corpus, context: context, calendar: SanctoralCalendar(entries: bundle.calendar))
    let hour = try #require(assembler.assembleVespers(day: 5, month: 4, year: 2026, priest: true))

    let fixtureText = try #require(try await OracleFixture.shared.spotCheck(filename: "2026-04-05_priestY_latin_easter.txt"))
    let diff = mismatches(hour: hour, fixtureText: fixtureText, sectionKinds: [.introductio, .conclusio])
    #expect(diff.isEmpty, "\(diff.count) unit(s) not found in the oracle fixture:\n\(diff.joined(separator: "\n"))")
}
