import Testing
@testable import BreviariumKit

// Diffs engine output against data/oracle-fixtures/ (generated by
// scripts/generate-oracle-fixtures against the pinned Divinum Officium checkout).
// Real fixtures and comparisons land in M4; this placeholder keeps the target buildable
// and the test suite green in the meantime.
@Test func oracleTargetIsWired() {
    #expect(breviariumKitDataFormatVersion > 0)
}
